version: '3'
services:
  db1:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mydb:/var/lib/mysql
volumes:
  mydb:
    driver: local